CREATE TABLE CONSUMER (
	CONSUMER_ID INT(20) AUTO_INCREMENT,
        NAME VARCHAR(200)  NOT NULL,
        PHONE_NUM CHAR(10)  NOT NULL,
        EMAIL_ADDRESS VARCHAR(100)  NOT NULL,
        PASSWORD VARCHAR(200) NOT NULL,
        BIRTH_DATE DATE,
        HEIGHT CHAR (3),
        WEIGHT CHAR (3),
        ADDRESS VARCHAR (200),
        GENDER VARCHAR (10),
        CREATED_DT DATETIME,
        LAST_UPDATED_DT DATETIME,
        PRIMARY KEY (CONSUMER_ID)
);

CREATE TABLE CONSUMER_LOGIN (
	CONSUMER_LOGIN_ID INT(20) AUTO_INCREMENT,
	CONSUMER_ID INT(20),
        AUTH_KEY VARCHAR(128)  NOT NULL,
        PUSH_DEVICE_ID VARCHAR(1000)  NOT NULL,
        DEVICE_OS VARCHAR(100)  NOT NULL,
        OS_VERSION VARCHAR(200) NOT NULL,
        LOGIN_DATE DATETIME,
        LOGOUT_DATE DATETIME,
        IP_ADDRESS VARCHAR(20),
        PRIMARY KEY (CONSUMER_LOGIN_ID)
);